name: ⚒️ Build and test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy rustfmt

      - name: Build
        run: make build-dev

      - name: Lint
        run: make lint

      - name: Unit Tests
        run: make test-unit

      - name: Integration Tests
        run: make test-integration

      - name: Docs tests
        run: make test-docs

      - name: Formatting
        run: make fmt-check
